### ISSUE TITLE
リスト 4.17: example_userで使うコード の説明をしてほしい

### ISSUE THREAD

**Issue by leonapo** [leonapo/toy_app#10]
リスト 4.17: example_userで使うコード

```
example_user.rb
 class User
  attr_accessor :name, :email

  def initialize(attributes = {})
    @name  = attributes[:name]
    @email = attributes[:email]
  end

  def formatted_email
    "#{@name} <#{@email}>"
  end
end
```

**Comment by hayashi-seiya** [comment]
※ このコメントで説明するクラスとインスタンスについては、下記のような漠然としたイメージで構いません。

　 | クラス | インスタンス | コードに起こすと
--- | --- | --- | --- 
例1 | 男 | マイケルジョーダン | マイケルジョーダン = 男.new
例2 | 車 | エスティマ | エスティマ = 車.new
例3 | 卵料理 | オムレツ | オムレツ = 卵料理.new

---

以下は、Userの振る舞いを定義するクラスです。
この状態ではUserがどのような振る舞いをするのかわかりません。

```ruby
class User
  ...
end
```

`#initialize` メソッドは、Userクラスのインスタンスを作成する時に、必ず呼ばれるメソッドです。
つまり、以下のコードでは、Userクラスのインスタンスを作成する際には
`attributes` というハッシュの中にある `name` と `email` を `@name` と `@email` に代入するよ、ということです。

```ruby
class User
  def initialize(attributes = {})
    @name  = attributes[:name]
    @email = attributes[:email]
  end
end
```


以下のコードでは、Userクラスのインスタンスの@nameと@emailにアクセスできるようになります。

```ruby
class User
  attr_accessor :name, :email

  def initialize(attributes = {})
    @name  = attributes[:name]
    @email = attributes[:email]
  end
end
```

具体的には

```ruby
user = User.new(name: "leon")
user.name # attr_accessor :name があるので、Userクラスの@nameにアクセスできます。呼び出しはnameだけど
=> "leon"

user = User.new(email: "leon@example.com")
user.email
=> "leon@example.com"

user = User.new # new時に引数を渡していないので、nameもemailも設定されていません
user.name
=> nil
```

となります。
ここで `user` はUserクラスのインスタンスを指します。
たとえば `user = User.new(name: "leon")` の `user` は `name` が `leon` のある特定のユーザーです。

---

つまりこのUserクラスは、nameとemailという値を持っており、それらを呼べば教えてくれて、
`user.formatted_email` とすると、 `名前 <メールアドレス>` という値を返してくれるクラスになります。
