### ISSUE TITLE
あとブラウザ上でコマンド＋Fで検索みたいな、よく使うショートカットもおしえてほしい

### ISSUE THREAD

**Issue by leonapo** [leonapo/toy_app#13]
シゴト上で、効率上がるようなことはこまめにおしえてほしい

**Comment by leonapo** [comment]
シゴト上というか、mac上で

**Comment by hayashiseiya** [comment]
## chrome
- タブを閉じる
  - ⌘ + w
- タブを移動する
  - ⌘ + shift + [ or ]

## alfred
mac内のアプリケーションたファイルを探せるツール
[Alfred \- Productivity App for Mac OS X](https://www.alfredapp.com/)

使い方は option + space で検索窓が出てくるので、検索したい物の名前を入力するだけ

## iterm
- 画面を縦に分割
  - ⌘ + d
- 画面を横に分割
  - ⌘ + shift + d


とかがよく使うかな💡
