### ISSUE TITLE
6.3 セキュアなパスワードを追加する

### ISSUE THREAD

**Issue by leonapo** [leonapo/toy_app#14]
```ユーザーの認証は、パスワードの送信、ハッシュ化、データベース内のハッシュ化された値との比較、という手順で進んでいきます。比較の結果が一致すれば、送信されたパスワードは正しいと認識され、そのユーザーは認証されます。ここで、生のパスワードではなく、ハッシュ化されたパスワード同士を比較していることに注目してください。こうすることで、生のパスワードをデータベースに保存するという危険なことをしなくてもユーザーを認証できます。これで、仮にデータベースの内容が盗まれたり覗き見されるようなことがあっても、パスワードの安全性が保たれます```

ハッシュ関数はブラックボックス化されてて、ハッシュ関数を通す前後で違う値を返してくれるのはわかるんだけど
前→後はできるのに、後→前はできないの？

**Comment by leonapo** [comment]
ここから、パスワードの話よくわかってない

**Comment by hayashi-seiya** [comment]
後->前できないです。

それができてしまうと、例えばハッシュ化されたパスワードが盗み出されたら、元のパスワードが復元できてしまうからです。
( どんなパスワード暗号化のロジックは、どんなものか忘れちゃいましたが・・・ )
