### ISSUE TITLE
6.4.1 本章のまとめ

### ISSUE THREAD

**Issue by leonapo** [leonapo/toy_app#16]
```正規表現は謎めいて見えるが非常に強力である```

正規表現って何だ？

**Comment by hayashiseiya** [comment]
検索する際に曖昧な文字を文字列を検索したい時に使えるパターンみたいなものです
例えば、

- 英数字が含まれていな文字列
- 最後に `.rb` がつく文字列

等々...

以下の記事を参考にしてください🙏
[押さえておきたい！正規表現の利用方法をわかりやすく解説｜ferret \[フェレット\]](https://ferret-plus.com/8391)
