### ISSUE TITLE
『Strong Parameters』これ、意味わからないから飛ばしました

### ISSUE THREAD

**Issue by leonapo** [leonapo/toy_app#20]

**Comment by hayashiseiya** [comment]
クライアントサイドからサーバーサイドにパラメーターを渡す際 (formに有力した値をsubmitする場合)、ユーザーから不正な値が送信される可能性があるので、それを検知して許可したもののみサーバーサイドで扱えるようにした仕組みのことを、ストロングパラメーターズと言います

簡単に説明してある以下の記事が少しでも参考になるかと🙏
[【Ruby on Rails】require と permit の使い方がよく分からない \- きゃまなかのブログ](http://techblog.kyamanak.com/entry/2017/08/29/012909)

**Comment by leonapo** [comment]
これはスカイプで口頭説明お願いします。

**Comment by hayashiseiya** [comment]
了解っす🙏
