### ISSUE TITLE
画像にキャプションを入れるソフトはなにを使ってるの？

### ISSUE THREAD

**Issue by leonapo** [leonapo/toy_app#21]
![image](https://user-images.githubusercontent.com/26695560/39118292-0d35a18a-4724-11e8-8bc3-756b6edb6bfc.png)

この『やじるし』とか『文字』は何を使って編集しているの？

**Comment by hayashiseiya** [comment]
俺も知りたい🙄
だいたいMacのプレビューでやります
(そんなやらないけど)
