### ISSUE TITLE
github  とslackを連携できない

### ISSUE THREAD

**Issue by leonapo** [leonapo/toy_app#7]
https://hawksnowlog.blogspot.jp/2017/02/notify-github-issue-to-slack.html
言われた通りに、
1、slack側にgithubをインストール
2、github側にslack連携許可
3、slackアプリ内でgithubにログイン

```
/github subscribe owner/repository
Either the app isn't installed on your repository or the repository does not exist. Install it to proceed.
＿Note: You will need to ask the owner of the repository to install it for you. Give them this link.＿
```
```
/github subscribe list
#レイルズ is subscribed to 0 repositories
```

**issueの通知をslackに飛ばせるようにしたい**

**Comment by hayashi-seiya** [comment]
@leonapo github integrationは賛成です 👌 
けど、Slackの#レイルズに流すよりかは、 #info-githubみたいになところに流した方が、#レイルズの会話も遮らないので、そっちの方がいいかと思いました🙏

**Comment by hayashi-seiya** [comment]
@leonapo テスト

**Comment by hayashi-seiya** [comment]
@leonapo テストです
